---
# This role configures a RAID device with all the available Azure disks

- fail: msg="Variable raid_file_system was not defined. Specify ext4 or xfs"
  when: raid_file_system is not defined
- debug: msg="raid file system is {{ raid_file_system }}"

- fail: msg="Variable raid_mountpoint was not defined. Specify a directory"
  when: raid_mountpoint is not defined
- debug: msg="Mount point is {{ raid_mountpoint }}"

- fail: msg="Variable raid_device was not defined. Specify /dev/md[number]"
  when: raid_device is not defined
- debug: msg="Raid device is {{ raid_device }}"

- name: Install Ubuntu packages
  apt: name={{ item }} state=latest
  with_items:
  - mdadm
  - xfsprogs

- name: "check for RAID device"
  command: mdadm -D {{ raid_device }}
  register: mdadm_check
  failed_when: mdadm_check.rc == 0

- name: "List data disks and exclude system reserved devices"
  shell: ls  /dev/sd* | egrep -v "/dev/sda|/dev/sdb" |egrep -v "[0-9]$"
  register: data_devices

- name: "Abort if RAID is not needed"
  fail: " {{ data_devices.stdout_lines | length }} devices detected.NO RAID is needed"
  when: "{{ data_devices.stdout_lines | length }} <= 1"

- debug: msg="{{ data_devices.stdout_lines | length }} Data disks detected {{ data_devices.stdout_lines | join('') }}"

- name: "Create RAID device"
  shell: echo yes | mdadm --create --verbose {{ raid_device }} --name=data --level=0 --raid-devices={{ data_devices.stdout_lines | length }} {{ data_devices.stdout_lines | join(" ") }}

- name: "Create filesystem"
  filesystem: >
   fstype={{ raid_file_system }}
   dev={{ raid_device }}
   force=no

- name: "Create mountpoint for  RAID"
  file: >
    path={{ raid_mountpoint }}
    state=directory

- name: "Mount RAID"
  mount: >
    name={{ raid_mountpoint }}
    src={{ raid_device }}
    fstype={{ raid_file_system }}
    state=mounted
    opts=defaults,noatime
